kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go version
  - go get ./...
  - go build
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.2
  - golangci-lint run
  - ./q system
  - go test -v -race -coverpkg=./... -coverprofile=coverage.txt

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov-token
    files:
      - coverage.txt
