linters:
  disable:
    - exhaustive
    - exhaustivestruct
    - errorlint
    - funlen
    - gocognit
    - gochecknoglobals
    - gocyclo
    - godot
    - goerr113
    - gofumpt
    - gomnd
    - gosec
    - lll
    - nestif
    - nlreturn
    - stylecheck
    - wrapcheck
    - wsl
